### PR TITLE
Update status after configuration

### PR DESCRIPTION
**Pull request by albertodonato**
Set the status to active after the vhost has been reconfigured

### CODE REVIEW

**Comment by marcoceppi** [comment]
I actually disagree with this code. Just because nginx is installed doesn't mean layers above it are ready.

**Comment by adam-stokes** [comment]
Won't the layers above it override this status anyway?

**Comment by albertodonato** [comment]
if the configure_site function sets the state to "maintenance", IMHO it should also unset it.
An alternative would be not to set it at all, and leave to the calling code to handle states when needed.

Prior to this change, a simple call to configure_site would leave the unit in "maintenance" unless the charm using the layer implements workload status

**Comment by adam-stokes** [comment]
I like the status_set telling us that NGINX is active (ready) and then letting the top layers set their own statuses when needed

**Comment by sparkiegeek** [comment]
I think layers other than the top should not be able to set_status. They need to advise their parent layer of their state, but don't have enough of a view on things to be able to set the status of the unit as a whole.

I totally agree with the idea of the symmetry though, if Nginx layer is saying it's in maintenance, it definitely needs to say when it's not in maintenance too.

**Pull request merged**
